// routes/versionRoutes.js
// ─────────────────────────────────────────────────────────
// All routes require a valid JWT (protect middleware).
//
// POST /api/versions/save      — save a code snapshot
// GET  /api/versions/:roomId   — get version history for a room
//
// This replaces the frontend mock array in your VersionHistory.jsx.
// The response shape matches what VersionHistory already expects:
//   { id, timestamp, preview, code }
// ─────────────────────────────────────────────────────────

const express = require("express");
const Version = require("../models/Version");
const Room    = require("../models/Room");
const protect = require("../middleware/auth");

const router = express.Router();
router.use(protect);

// ── POST /api/versions/save ────────────────────────────────
// Body: { roomId, code }
// Creates a snapshot and updates room.currentCode simultaneously.
router.post("/save", async (req, res) => {
  try {
    const { roomId, code } = req.body;

    if (!roomId || !code) {
      return res.status(400).json({ message: "roomId and code are required" });
    }

    const room = await Room.findOne({ roomId });
    if (!room) {
      return res.status(404).json({ message: "Room not found" });
    }

    // Check membership + permission
    const member = room.members.find(
      (m) => m.user.toString() === req.user.id
    );
    if (!member || member.role === "viewer") {
      return res.status(403).json({ message: "Viewers cannot save versions" });
    }

    // Save snapshot (preview auto-generated by pre-save hook in Version model)
    const version = await Version.create({
      room: room._id,
      code,
      savedBy: req.user.id,
    });

    // Also update the room's live code
    room.currentCode = code;
    await room.save();

    res.status(201).json({ version });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// ── GET /api/versions/:roomId ──────────────────────────────
// Returns version list newest-first.
// Shape matches VersionHistory.jsx: { id, timestamp, preview, code }
router.get("/:roomId", async (req, res) => {
  try {
    const room = await Room.findOne({ roomId: req.params.roomId });
    if (!room) {
      return res.status(404).json({ message: "Room not found" });
    }

    const versions = await Version.find({ room: room._id })
      .populate("savedBy", "name")
      .sort({ createdAt: -1 }); // newest first — matches sidebar order

    // Shape the response to match your VersionHistory component's expectations
    const shaped = versions.map((v) => ({
      id: v._id,
      code: v.code,
      preview: v.preview,
      timestamp: v.createdAt.toLocaleString("en-IN", {
        dateStyle: "medium",
        timeStyle: "short",
      }),
      savedBy: v.savedBy?.name || "Unknown",
    }));

    res.json({ versions: shaped });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
